-- ============================================================================
-- PezMax 业务表结构：MySQL 8 → PostgreSQL 16 迁移 DDL
-- 来源：ptmj-platform (1).sql（2026-09-16 完整 dump），10 张 ptmj_* 业务表
-- 映射规则（见 docs/pezmax-desktop-go-migration.md §7.3）：
--   tinyint        -> smallint          （保持 0/1/2 语义，不改 boolean）
--   datetime       -> timestamp         （不带时区，与 MySQL datetime 对应）
--   AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--                     （必须 BY DEFAULT 以便 ETL 插入旧 ID；START WITH 取自
--                       原 dump 的 AUTO_INCREMENT 值，先建表后迁数据期间
--                       新插入的行也不会与旧数据冲突）
--   ON UPDATE CURRENT_TIMESTAMP 已移除：update_time 由 Go 侧显式维护
-- 字段名/怪癖原样保留：creat_by/creat_time 拼写、ptmj_bookmark_favorite 的
-- int 类型与单列主键等，与源库一致以保证 RuoYi 风格 SQL 平移可用。
-- 脚本幂等：可重复执行（CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS）。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. 平台用户表（桌面端双轨用户体系，密码 BCrypt 原样迁移）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_user (
    user_id     bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 455) PRIMARY KEY,
    user_name   varchar(255) NOT NULL,
    password    varchar(255) NOT NULL DEFAULT '',
    avatar      varchar(255) DEFAULT '',
    count       int DEFAULT 0,
    status      char(1) DEFAULT '1',
    creat_by    varchar(64) DEFAULT '',
    create_time timestamp,
    update_by   varchar(64) DEFAULT '',
    update_time timestamp,
    remark      varchar(500) DEFAULT ''
);
COMMENT ON TABLE ptmj_user IS '平台用户表';
COMMENT ON COLUMN ptmj_user.count IS '上传文件数量（冗余计数，Go 侧事务维护）';
COMMENT ON COLUMN ptmj_user.status IS '账号状态（0为封禁，1为正常，与RuoYi相反）';
COMMENT ON COLUMN ptmj_user.creat_by IS '创建者（源库拼写如此，原样保留）';

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_name ON ptmj_user (user_name);

-- ---------------------------------------------------------------------------
-- 2. 用户密保表（一用户一行，密保问答以 | 分隔存储）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_security (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 453) PRIMARY KEY,
    user_id     bigint NOT NULL,
    question    varchar(500) NOT NULL,
    answer      varchar(500) NOT NULL,
    create_by   varchar(64) DEFAULT '',
    create_time timestamp,
    update_by   varchar(64) DEFAULT '',
    update_time timestamp,
    remark      varchar(500) DEFAULT ''
);
COMMENT ON TABLE ptmj_security IS '用户密保表';
COMMENT ON COLUMN ptmj_security.answer IS '密保答案（BCrypt 密文，原样迁移）';

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_id ON ptmj_security (user_id);

-- ---------------------------------------------------------------------------
-- 3. 试卷文件表（核心；复合主键含自增列）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_file (
    file_id      bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1007),
    user_id      bigint NOT NULL,
    file_name    varchar(255) NOT NULL,
    file_url     varchar(500) NOT NULL,
    file_size    bigint,
    file_format  varchar(20),
    file_year    int,
    file_type    smallint,
    file_school  varchar(100),
    file_subject varchar(64) NOT NULL,
    reviewer     varchar(64),
    file_status  smallint DEFAULT 0,
    del_flag     smallint DEFAULT 0,
    create_by    varchar(64),
    create_time  timestamp DEFAULT CURRENT_TIMESTAMP,
    update_by    varchar(64),
    update_time  timestamp DEFAULT CURRENT_TIMESTAMP,
    remark       varchar(500),
    PRIMARY KEY (file_id, user_id)
);
COMMENT ON TABLE ptmj_file IS '试卷文件表';
COMMENT ON COLUMN ptmj_file.file_type IS '文件类型：1-期末，2-期中，3-资料，4-补考，5-其他学校';
COMMENT ON COLUMN ptmj_file.file_status IS '文件状态：0-未审核，1-通过，2-未通过，3-被举报';
COMMENT ON COLUMN ptmj_file.del_flag IS '删除标记：0-未删除，1-已删除';
COMMENT ON COLUMN ptmj_file.remark IS '备注（复用为 MinIO 文件夹相对路径）';
COMMENT ON COLUMN ptmj_file.file_url IS '文件URL：minioUrl/bucket/objectName，bucket 沿用 ptmj';

CREATE INDEX IF NOT EXISTS idx_upload_user_id ON ptmj_file (user_id);
CREATE INDEX IF NOT EXISTS idx_file_year      ON ptmj_file (file_year);
CREATE INDEX IF NOT EXISTS idx_file_type      ON ptmj_file (file_type);
CREATE INDEX IF NOT EXISTS idx_file_status    ON ptmj_file (file_status);
CREATE INDEX IF NOT EXISTS idx_del_flag       ON ptmj_file (del_flag);
CREATE INDEX IF NOT EXISTS idx_file_school    ON ptmj_file (file_school);

-- ---------------------------------------------------------------------------
-- 4. 试卷下载表（creat_by/creat_time 为源库拼写，原样保留）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_file_download (
    download_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 590),
    file_id     bigint NOT NULL,
    user_id     bigint NOT NULL,
    creat_by    varchar(64),
    creat_time  timestamp,
    update_by   varchar(64),
    update_time timestamp,
    remark      varchar(500),
    PRIMARY KEY (download_id, file_id, user_id)
);
COMMENT ON TABLE ptmj_file_download IS '试卷下载表';

-- ---------------------------------------------------------------------------
-- 5. 试卷收藏表（纯关联表，无自增）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_file_favorite (
    file_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (file_id, user_id)
);
COMMENT ON TABLE ptmj_file_favorite IS '试卷收藏表';

CREATE INDEX IF NOT EXISTS dld_usr_id ON ptmj_file_favorite (user_id);

-- ---------------------------------------------------------------------------
-- 6. 举报表（资料举报）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_report (
    report_id   bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 22) PRIMARY KEY,
    file_id     bigint NOT NULL,
    user_id     bigint NOT NULL,
    reason      varchar(500) NOT NULL,
    result      char(1) DEFAULT '0',
    create_by   varchar(64),
    create_time timestamp,
    update_by   varchar(64),
    update_time timestamp,
    remark      varchar(255)
);
COMMENT ON TABLE ptmj_report IS '举报表';
COMMENT ON COLUMN ptmj_report.result IS '审核结果（0未审核 1属实 2不属实）';

-- ---------------------------------------------------------------------------
-- 7. 外部书签表
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_bookmark (
    id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 22) PRIMARY KEY,
    user_id       bigint NOT NULL,
    url           varchar(512) NOT NULL,
    title         varchar(500) NOT NULL,
    description   text,
    cover_image   varchar(1000),
    subject       varchar(64),
    resource_type varchar(32) DEFAULT 'other',
    collection    varchar(64),
    status        smallint DEFAULT 0,
    del_flag      smallint DEFAULT 0,
    create_by     varchar(64),
    create_time   timestamp DEFAULT CURRENT_TIMESTAMP,
    update_by     varchar(64),
    update_time   timestamp DEFAULT CURRENT_TIMESTAMP,
    remark        text
);
COMMENT ON TABLE ptmj_bookmark IS '外部书签表';
COMMENT ON COLUMN ptmj_bookmark.resource_type IS '资源类型：course/blog/paper/tool/entertainment/other';
COMMENT ON COLUMN ptmj_bookmark.status IS '书签状态：0-未审核，1-通过，2-未通过，3-被举报';
COMMENT ON COLUMN ptmj_bookmark.del_flag IS '删除标记：0-未删除，1-已删除';

CREATE INDEX IF NOT EXISTS idx_bookmark_user_id       ON ptmj_bookmark (user_id);
CREATE INDEX IF NOT EXISTS idx_bookmark_subject       ON ptmj_bookmark (subject);
CREATE INDEX IF NOT EXISTS idx_bookmark_resource_type ON ptmj_bookmark (resource_type);
CREATE INDEX IF NOT EXISTS idx_bookmark_collection    ON ptmj_bookmark (collection);
CREATE INDEX IF NOT EXISTS idx_bookmark_status        ON ptmj_bookmark (status);
CREATE INDEX IF NOT EXISTS idx_bookmark_del_flag      ON ptmj_bookmark (del_flag);
CREATE INDEX IF NOT EXISTS idx_bookmark_create_time   ON ptmj_bookmark (create_time);

-- ---------------------------------------------------------------------------
-- 8. 书签收藏表（源库即 int 类型且主键仅 bookmark_id，原样保留）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_bookmark_favorite (
    bookmark_id int NOT NULL,
    user_id     int,
    PRIMARY KEY (bookmark_id)
);
COMMENT ON TABLE ptmj_bookmark_favorite IS '书签收藏表（源库主键仅 bookmark_id，原样保留）';

-- ---------------------------------------------------------------------------
-- 9. 书签举报表（原 idx_create_time 与 ptmj_bookmark 重名，改名 idx_bmr_create_time）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_bookmark_report (
    report_id   bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 20) PRIMARY KEY,
    bookmark_id bigint NOT NULL,
    user_id     bigint NOT NULL,
    reason      varchar(500) NOT NULL,
    result      char(1) NOT NULL DEFAULT '0',
    create_by   varchar(64),
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   varchar(64),
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark      varchar(500),
    CONSTRAINT uk_user_bookmark UNIQUE (user_id, bookmark_id)
);
COMMENT ON TABLE ptmj_bookmark_report IS '书签举报表';
COMMENT ON COLUMN ptmj_bookmark_report.result IS '审核结果：0-未审核，1-属实，2-不属实';

CREATE INDEX IF NOT EXISTS idx_bookmark_id    ON ptmj_bookmark_report (bookmark_id);
CREATE INDEX IF NOT EXISTS idx_user_id        ON ptmj_bookmark_report (user_id);
CREATE INDEX IF NOT EXISTS idx_result         ON ptmj_bookmark_report (result);
CREATE INDEX IF NOT EXISTS idx_bmr_create_time ON ptmj_bookmark_report (create_time);

-- ---------------------------------------------------------------------------
-- 10. 通知表（5 种类型：1版本更新 2系统故障 3系统维护 4资料下架 5日常滚动；
--     原 idx_target-user 含连字符，PG 非法，改名 idx_target_user）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ptmj_notification (
    notify_id               bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 15) PRIMARY KEY,
    notify_type             char(1) NOT NULL,
    title                   varchar(200) NOT NULL,
    content                 text,
    status                  char(1) NOT NULL DEFAULT '0',
    sort                    int NOT NULL DEFAULT 0,
    display_mode            char(1) NOT NULL DEFAULT '0',
    fault_start_time        timestamp,
    fault_end_time          timestamp,
    maintenance_start_time  timestamp,
    maintenance_end_time    timestamp,
    remind_before_minutes   int,
    upload_user_id          bigint,
    material_id             bigint,
    material_title_snapshot varchar(500),
    publish_start           timestamp,
    publish_end             timestamp,
    scroll_time_interval    int DEFAULT 30,
    create_by               varchar(64),
    create_time             timestamp DEFAULT CURRENT_TIMESTAMP,
    update_by               varchar(64),
    update_time             timestamp DEFAULT CURRENT_TIMESTAMP,
    remark                  varchar(500),
    CONSTRAINT uk_material_notify UNIQUE (material_id)
);
COMMENT ON TABLE ptmj_notification IS '通知表';
COMMENT ON COLUMN ptmj_notification.notify_type IS '通知类型（1版本更新 2系统故障 3系统维护 4资料下架 5日常滚动）';
COMMENT ON COLUMN ptmj_notification.status IS '配置状态（0启用 1禁用）';
COMMENT ON COLUMN ptmj_notification.display_mode IS '展示形态（0弹窗 1滚动字幕）';
COMMENT ON COLUMN ptmj_notification.material_id IS '被举报下架的资料id（仅类型4；同一资料唯一）';
COMMENT ON COLUMN ptmj_notification.sort IS '排序/优先级（越大越优先弹出）';

CREATE INDEX IF NOT EXISTS idx_notify_type_status ON ptmj_notification (notify_type, status);
CREATE INDEX IF NOT EXISTS idx_target_user        ON ptmj_notification (upload_user_id);
CREATE INDEX IF NOT EXISTS idx_publish            ON ptmj_notification (publish_start, publish_end);
