// Package datum is the data layer for the PezMax desktop business tables
// (ptmj_*). It provides the idempotent schema bootstrap plus repositories
// consumed by the /datum/* desktop handlers (profile, files, downloads,
// favorites, reports, notifications).
//
// The DDL below mirrors k_admin/sql/ptmj_schema.sql (the docker initdb
// source). The two must stay in sync: the SQL file seeds fresh containers,
// EnsureSchema heals any database the Go binary starts against — including
// existing ptmj databases migrated from MySQL, since every statement is
// IF NOT EXISTS and identity START WITH values only apply to fresh tables.
package datum

import (
	"fmt"

	"github.com/GoAdminGroup/go-admin/modules/db"
)

var schemaStatements = []string{
	// 1. 平台用户表（桌面端双轨用户体系，密码 BCrypt 原样迁移）
	`CREATE TABLE IF NOT EXISTS ptmj_user (
		user_id     bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 455) PRIMARY KEY,
		user_name   varchar(255) NOT NULL,
		password    varchar(255) NOT NULL DEFAULT '',
		avatar      varchar(255) DEFAULT '',
		count       int DEFAULT 0,
		status      char(1) DEFAULT '1',
		creat_by    varchar(64) DEFAULT '',
		create_time timestamp,
		update_by   varchar(64) DEFAULT '',
		update_time timestamp,
		remark      varchar(500) DEFAULT ''
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS uk_user_name ON ptmj_user (user_name)`,

	// 2. 用户密保表（一用户一行，密保问答以 | 分隔存储）
	`CREATE TABLE IF NOT EXISTS ptmj_security (
		id          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 453) PRIMARY KEY,
		user_id     bigint NOT NULL,
		question    varchar(500) NOT NULL,
		answer      varchar(500) NOT NULL,
		create_by   varchar(64) DEFAULT '',
		create_time timestamp,
		update_by   varchar(64) DEFAULT '',
		update_time timestamp,
		remark      varchar(500) DEFAULT ''
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS uk_user_id ON ptmj_security (user_id)`,

	// 3. 试卷文件表（核心；复合主键含自增列）
	`CREATE TABLE IF NOT EXISTS ptmj_file (
		file_id      bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1007),
		user_id      bigint NOT NULL,
		file_name    varchar(255) NOT NULL,
		file_url     varchar(500) NOT NULL,
		file_size    bigint,
		file_format  varchar(20),
		file_year    int,
		file_type    smallint,
		file_school  varchar(100),
		file_subject varchar(64) NOT NULL,
		reviewer     varchar(64),
		file_status  smallint DEFAULT 0,
		del_flag     smallint DEFAULT 0,
		create_by    varchar(64),
		create_time  timestamp DEFAULT CURRENT_TIMESTAMP,
		update_by    varchar(64),
		update_time  timestamp DEFAULT CURRENT_TIMESTAMP,
		remark       varchar(500),
		PRIMARY KEY (file_id, user_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_upload_user_id ON ptmj_file (user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_file_year      ON ptmj_file (file_year)`,
	`CREATE INDEX IF NOT EXISTS idx_file_type      ON ptmj_file (file_type)`,
	`CREATE INDEX IF NOT EXISTS idx_file_status    ON ptmj_file (file_status)`,
	`CREATE INDEX IF NOT EXISTS idx_del_flag       ON ptmj_file (del_flag)`,
	`CREATE INDEX IF NOT EXISTS idx_file_school    ON ptmj_file (file_school)`,

	// 4. 试卷下载表（creat_by/creat_time 为源库拼写，原样保留）
	`CREATE TABLE IF NOT EXISTS ptmj_file_download (
		download_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 590),
		file_id     bigint NOT NULL,
		user_id     bigint NOT NULL,
		creat_by    varchar(64),
		creat_time  timestamp,
		update_by   varchar(64),
		update_time timestamp,
		remark      varchar(500),
		PRIMARY KEY (download_id, file_id, user_id)
	)`,

	// 5. 试卷收藏表（纯关联表，无自增）
	`CREATE TABLE IF NOT EXISTS ptmj_file_favorite (
		file_id bigint NOT NULL,
		user_id bigint NOT NULL,
		PRIMARY KEY (file_id, user_id)
	)`,
	`CREATE INDEX IF NOT EXISTS dld_usr_id ON ptmj_file_favorite (user_id)`,

	// 6. 举报表（资料举报）
	`CREATE TABLE IF NOT EXISTS ptmj_report (
		report_id   bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 22) PRIMARY KEY,
		file_id     bigint NOT NULL,
		user_id     bigint NOT NULL,
		reason      varchar(500) NOT NULL,
		result      char(1) DEFAULT '0',
		create_by   varchar(64),
		create_time timestamp,
		update_by   varchar(64),
		update_time timestamp,
		remark      varchar(255)
	)`,

	// 7. 外部书签表
	`CREATE TABLE IF NOT EXISTS ptmj_bookmark (
		id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 22) PRIMARY KEY,
		user_id       bigint NOT NULL,
		url           varchar(512) NOT NULL,
		title         varchar(500) NOT NULL,
		description   text,
		cover_image   varchar(1000),
		subject       varchar(64),
		resource_type varchar(32) DEFAULT 'other',
		collection    varchar(64),
		status        smallint DEFAULT 0,
		del_flag      smallint DEFAULT 0,
		create_by     varchar(64),
		create_time   timestamp DEFAULT CURRENT_TIMESTAMP,
		update_by     varchar(64),
		update_time   timestamp DEFAULT CURRENT_TIMESTAMP,
		remark        text
	)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_user_id       ON ptmj_bookmark (user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_subject       ON ptmj_bookmark (subject)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_resource_type ON ptmj_bookmark (resource_type)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_collection    ON ptmj_bookmark (collection)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_status        ON ptmj_bookmark (status)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_del_flag      ON ptmj_bookmark (del_flag)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_create_time   ON ptmj_bookmark (create_time)`,

	// 8. 书签收藏表（源库即 int 类型且主键仅 bookmark_id，原样保留）
	`CREATE TABLE IF NOT EXISTS ptmj_bookmark_favorite (
		bookmark_id int NOT NULL,
		user_id     int,
		PRIMARY KEY (bookmark_id)
	)`,

	// 9. 书签举报表（idx_create_time 与 ptmj_bookmark 重名，改名 idx_bmr_create_time）
	`CREATE TABLE IF NOT EXISTS ptmj_bookmark_report (
		report_id   bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 20) PRIMARY KEY,
		bookmark_id bigint NOT NULL,
		user_id     bigint NOT NULL,
		reason      varchar(500) NOT NULL,
		result      char(1) NOT NULL DEFAULT '0',
		create_by   varchar(64),
		create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		update_by   varchar(64),
		update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
		remark      varchar(500),
		CONSTRAINT uk_user_bookmark UNIQUE (user_id, bookmark_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_bookmark_id     ON ptmj_bookmark_report (bookmark_id)`,
	`CREATE INDEX IF NOT EXISTS idx_user_id         ON ptmj_bookmark_report (user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_result          ON ptmj_bookmark_report (result)`,
	`CREATE INDEX IF NOT EXISTS idx_bmr_create_time ON ptmj_bookmark_report (create_time)`,

	// 10. 通知表（idx_target-user 含连字符 PG 非法，改名 idx_target_user）
	`CREATE TABLE IF NOT EXISTS ptmj_notification (
		notify_id               bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 15) PRIMARY KEY,
		notify_type             char(1) NOT NULL,
		title                   varchar(200) NOT NULL,
		content                 text,
		status                  char(1) NOT NULL DEFAULT '0',
		sort                    int NOT NULL DEFAULT 0,
		display_mode            char(1) NOT NULL DEFAULT '0',
		fault_start_time        timestamp,
		fault_end_time          timestamp,
		maintenance_start_time  timestamp,
		maintenance_end_time    timestamp,
		remind_before_minutes   int,
		upload_user_id          bigint,
		material_id             bigint,
		material_title_snapshot varchar(500),
		publish_start           timestamp,
		publish_end             timestamp,
		scroll_time_interval    int DEFAULT 30,
		create_by               varchar(64),
		create_time             timestamp DEFAULT CURRENT_TIMESTAMP,
		update_by               varchar(64),
		update_time             timestamp DEFAULT CURRENT_TIMESTAMP,
		remark                  varchar(500),
		CONSTRAINT uk_material_notify UNIQUE (material_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_notify_type_status ON ptmj_notification (notify_type, status)`,
	`CREATE INDEX IF NOT EXISTS idx_target_user        ON ptmj_notification (upload_user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_publish            ON ptmj_notification (publish_start, publish_end)`,
}

// EnsureSchema creates the ten ptmj_* business tables and their indexes when
// missing. It is idempotent and safe to run against a database that already
// carries migrated production data.
func EnsureSchema(conn db.Connection) error {
	if conn == nil {
		return fmt.Errorf("datum database connection is required")
	}
	for _, statement := range schemaStatements {
		if _, err := conn.Exec(statement); err != nil {
			return fmt.Errorf("initialize datum schema: %w", err)
		}
	}
	return nil
}
